// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqwyuanlhhlofqxvrlqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxd3l1YW5saGhsb2ZxeHZybHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDg1MDIsImV4cCI6MjA2NDc4NDUwMn0.SA5hlbU-uOyc8kodzD2lu0Yzq5ZgEE3VzBhfIZYZLss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);